# Generated by Django 3.2.3 on 2021-06-05 10:03

import crypto_fifo_taxes.enums
import crypto_fifo_taxes.utils.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Name')),
                ('icon', models.ImageField(upload_to='coin_icons', verbose_name='Icon')),
                ('is_fiat', models.BooleanField(default=False, verbose_name='Is FIAT')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_pairs', to='crypto_fifo_taxes.currency')),
                ('sell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sell_pairs', to='crypto_fifo_taxes.currency')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_price', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('timestamp', models.DateTimeField()),
                ('description', models.TextField(blank=True, default='')),
                ('trade_type', enumfields.fields.EnumField(enum=crypto_fifo_taxes.enums.TradeType, max_length=10)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades', to='crypto_fifo_taxes.currencypair')),
            ],
        ),
        migrations.CreateModel(
            name='TradeFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='crypto_fifo_taxes.currency')),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='crypto_fifo_taxes.trade')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Wallet Name')),
                ('icon', models.ImageField(upload_to='wallet_icons', verbose_name='Icon')),
                ('fiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='crypto_fifo_taxes.currency', verbose_name='FIAT')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_amount', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('to_amount', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_transfers', to='crypto_fifo_taxes.currency')),
                ('from_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to='crypto_fifo_taxes.wallet')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_transfers', to='crypto_fifo_taxes.currency')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfers', to='crypto_fifo_taxes.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='TradeFeeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('to_cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='crypto_fifo_taxes.tradefee')),
            ],
        ),
        migrations.CreateModel(
            name='TradeExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('to_cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fee_cost', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('trade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='crypto_fifo_taxes.trade')),
            ],
        ),
        migrations.AddField(
            model_name='trade',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='crypto_fifo_taxes.wallet'),
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('market_cap', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('volume', crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=10, default=Decimal('0'), max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='crypto_fifo_taxes.currency', verbose_name='Currency')),
                ('fiat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='crypto_fifo_taxes.currency', verbose_name='FIAT')),
            ],
            options={
                'unique_together': {('currency', 'date', 'fiat')},
            },
        ),
    ]
