# Generated by Django 3.2.3 on 2021-06-13 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tx_fee',
            new_name='fee_detail',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tx_from',
            new_name='from_detail',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='tx_to',
            new_name='to_detail',
        ),
    ]
