# Generated by Django 3.2.3 on 2021-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='coin_icons', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_icons', verbose_name='Icon'),
        ),
    ]
