# Generated by Django 3.2.4 on 2021-08-17 13:12

import crypto_fifo_taxes.enums
import crypto_fifo_taxes.utils.models
from decimal import Decimal
import django.core.validators
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0002_rename_detail_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyprice',
            name='market_cap',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='currencyprice',
            name='price',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='currencyprice',
            name='volume',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fee_amount',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gain',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_label',
            field=enumfields.fields.EnumField(default=0, enum=crypto_fifo_taxes.enums.TransactionLabel, max_length=10),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='cost_basis',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AlterField(
            model_name='transactiondetail',
            name='quantity',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(decimal_places=14, default=Decimal('0'), max_digits=32, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
