# Generated by Django 3.2.3 on 2021-06-12 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0002_make_icon_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransfer',
            name='timestamp',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='symbol',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='currencypair',
            unique_together={('buy', 'sell')},
        ),
    ]
