# Generated by Django 3.2.3 on 2021-06-12 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0003_add_timestamp_to_wallet_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeextra',
            name='fee_cost',
        ),
    ]
