# Generated by Django 3.2.4 on 2021-08-18 13:30

import crypto_fifo_taxes.enums
from django.db import migrations
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0004_add_id_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_label',
            field=enumfields.fields.EnumIntegerField(default=0, enum=crypto_fifo_taxes.enums.TransactionLabel),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=enumfields.fields.EnumIntegerField(default=0, enum=crypto_fifo_taxes.enums.TransactionType),
        ),
    ]
