# Generated by Django 3.2.4 on 2021-08-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0006_add_tx_order_ids'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
    ]
