# Generated by Django 3.2.8 on 2021-10-14 23:17

import crypto_fifo_taxes.utils.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto_fifo_taxes', '0008_combine_order_tx_id_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worth', crypto_fifo_taxes.utils.models.TransactionDecimalField(blank=True, decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(blank=True, decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SnapshotBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', crypto_fifo_taxes.utils.models.TransactionDecimalField(blank=True, decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cost_basis', crypto_fifo_taxes.utils.models.TransactionDecimalField(blank=True, decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='crypto_fifo_taxes.currency')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='crypto_fifo_taxes.snapshot')),
            ],
        ),
    ]
