# Generated by Django 3.2.8 on 2021-10-17 21:01

import crypto_fifo_taxes.utils.models
from decimal import Decimal
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0009_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='snapshot',
            name='deposits',
            field=crypto_fifo_taxes.utils.models.TransactionDecimalField(blank=True, decimal_places=14, default=Decimal('0'), max_digits=32, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
