# Generated by Django 3.2.8 on 2021-10-17 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0010_add_deposits_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snapshot',
            options={'ordering': ['date']},
        ),
    ]
