# Generated by Django 3.2.18 on 2024-02-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_fifo_taxes', '0012_txdetail_currency_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='Name'),
        ),
    ]
