# Generated by Django 5.0.2 on 2024-02-24 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_fifo_taxes", "0014_disallow_null_in_charfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyprice",
            name="num_missing_days",
            field=models.IntegerField(default=0),
        ),
    ]
