# Generated by Django 5.0.2 on 2024-03-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_fifo_taxes", "0015_add_num_missing_days"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="currencypair",
            unique_together=set(),
        ),
    ]
