# Generated by Django 5.0.2 on 2024-03-26 17:33
from datetime import timedelta

from django.db import migrations, models


def fix_duplicate_timestamps(apps, schema_editor):
    Transaction = apps.get_model("crypto_fifo_taxes", "Transaction")

    qs = Transaction.objects.values("timestamp").annotate(count=models.Count("timestamp")).filter(count__gt=1)
    for tx in qs:
        transactions = Transaction.objects.filter(timestamp=tx["timestamp"])
        for i, tx in enumerate(transactions):
            tx.timestamp = tx.timestamp + timedelta(microseconds=i)
            tx.save()


class Migration(migrations.Migration):
    dependencies = [
        ("crypto_fifo_taxes", "0016_remove_unique_together"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_timestamps, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="transaction",
            name="timestamp",
            field=models.DateTimeField(unique=True),
        ),
    ]
