# Generated by Django 5.0.2 on 2024-03-30 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crypto_fifo_taxes", "0017_make_tx_timestamp_unique"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snapshot",
            name="user",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="user",
        ),
    ]
